REGEDIT /s %LOCALAPPDATA%\BlueStacks\BstHdAndroidSvc.REG
REGEDIT /s %LOCALAPPDATA%\BlueStacks\BstHdLogRotatorSvc.REG
REGEDIT /s %LOCALAPPDATA%\BlueStacks\BstHdUpdaterSvc.REG
REGEDIT /s %LOCALAPPDATA%\BlueStacks\BsAgent32.REG
REGEDIT /s %LOCALAPPDATA%\BlueStacks\BsAgent64.REG